### ISSUE TITLE
algod docker image: kmd can't start due to memory limits

### ISSUE THREAD

**Issue by joe-p** [algorand/go-algorand#5273]
### Subject of the issue

KMD doesn't properly start in the official docker container

### Your environment

Running `algorand/algod:latest`

### Steps to reproduce

1. Set `START_CMD: true`
2. Attempt to use KMD

### Expected behaviour

KMD is up and can be used via the API

### Actual behaviour

KMD does not succesfully start due to memory limits:

```
time="2023-04-07T17:02:28.077918 +0000" level=info msg="failed to mlockall: cannot allocate memory" file=mlock_linux.go function=main.tryMlockall line=30
time="2023-04-07T17:02:28.079020 +0000" level=info msg="started kmd on sock: 127.0.0.1:7833" file=main.go function=main.runKmd line=118
time="2023-04-07T17:03:29.240028 +0000" level=info msg="killing kmd after timeout" file=server.go function="github.com/algorand/go-algorand/daemon/kmd/server.(*WalletServer).makeWatchdogCallback.func2" line=173
time="2023-04-07T17:03:29.243036 +0000" level=info msg="kmd wallet HTTP server stopped with: http: Server closed" file=server.go function="github.com/algorand/go-algorand/daemon/kmd/server.(*WalletServer).start.func2" line=277
time="2023-04-07T17:03:29.244036 +0000" level=info msg="kmd server died. exiting..." file=main.go function=main.runKmd line=122
```

I believe increasing the limit for `algorand` in `/etc/security/limits.conf` in the container would solve this

**Comment by winder** [comment]
I'm not able to reproduce this. One thing I see immediately is the wrong environment variable. You need `START_KMD=1`.

Here is how I ran the container:
```
docker run --rm -it \
             -p 4190:8080 \
             -p 4191:7833 \
             --name algod-test-run \
             -e TOKEN=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa \
             -e START_KMD=1 \
              algorand/algod:latest
```

KMD is running according to: `docker top algod-test-run`

**Comment by joe-p** [comment]
Weird, able to reproduce this on Max OS X. 

~/.docker/daemon.json:

```json
{
	"builder": { "gc": { "defaultKeepStorage": "20GB", "enabled": true } },
	"experimental": false,
	"features": { "buildkit": true }
}
```

The docker compose file I'm using:

```yml
services:
  algorand-node:
    image: algorand/algod:latest
    ports:
      - 4001:8080
      - 4002:7833
    environment:
      TOKEN: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
      KMD_TOKEN: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
      DEV_MODE: 'true'
      NETWORK: ''
      FAST_CATCHUP: true
      START_KMD: 1
      NUM_ROUNDS: 30000
      TELEMETRY_NAME: 'joe-p/docker-algorand'
```
