### ISSUE TITLE
Unable to override config.json

### ISSUE THREAD

**Issue by tom-gnade** [algorand/go-algorand#5743]
### Subject of the issue

When an override config.json file is provided, most of the values are ignored or overwritten by defaults.

### Steps to reproduce

1. Set up a docker image for a node - using docker compose, the compose.yaml file is:
```
  algorand:
    image: algomon/algorand/algod:latest
    ... (other values go here)
    volumes:
      - ./algorand/data:/algod/data
      - ./algorand/config.json:/etc/algorand/config.json
      - ./algorand/logging.config:/etc/algorand/logging.config
    environment:
      - NETWORK=mainnet
      - FAST_CATCHUP=1
      - START_KMD=1
      - TOKEN=a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1
```

2. Provide an override config.json file in ./algorand/config.json:
```
{
        "Archival": false,
        "GossipFanout": 4,
        "NetAddress": ":4190",
        "BaseLoggerDebugLevel": 4,
        "EndpointAddress": ":8082",
        "EnableMetricReporting": false,
        "NodeExporterPath": "/node/bin/node_exporter",
        "EnableRuntimeMetrics": false,
        "EnableLedgerService": false,
        "EnableBlockService": false
}
```

3. Run the container and observe the runtime values using $ docker exec -it algomon-algonode cat /algod/data/config.json

### Expected behaviour

The runtime values should be taken from the provided config.json file.

### Actual behaviour

Most of the values are overwritten:
```
{
        "Archival": true,
        "GossipFanout": 8,
        "NetAddress": ":4190",
        "EndpointAddress": "0.0.0.0:8080",
        "NodeExporterPath": "/node/bin/node_exporter",
        "EnableLedgerService": true,
        "EnableBlockService": true
}```
