### ISSUE TITLE
goal clerk compile without filesystem

### ISSUE THREAD

**Issue by jeapostrophe** [algorand/go-algorand#909]
`algorand/sandbox` is really useful for working with Algorand without a complicated dev environment. However, it is currently not set up to do any sort of `$PWD`-forwarding, so it is not really useful to use `./sandbox goal clerk compile` since the compiler is based around files.

It might be nice to change the sandbox to do something like that, one trick is to use `docker-compose` like this:

```
    cat<<EOF | docker-compose -f - run -w /pwd goal $*
version: '3'
services:
  algorand-goal:
    image: algorand-sandbox
    volumes:
      - $PWD:/pwd
EOF
```

But I think it would be better for `goal clerk compile` to directly support getting its input from `STDIN` and giving its output to `STDOUT` as well. `solc` has a pretty good model for this where it accepts all of the input and produces all of the output as a JSON object with everything as some field/etc.
